### ISSUE TITLE
CFP - 7º Meetup NUGCE 

### ISSUE THREAD

**Issue by cicerohen** [ssjsce/meetups#2]
# CFP - 7º Meetup NUGCE 
**[IFCE](https://www.google.com/maps/place/IFCE+-+Instituto+Federal+Cear%C3%A1+%7C+Campus+Fortaleza/@-3.7570613,-38.5672955,14z/data=!4m8!1m2!2m1!1sifce!3m4!1s0x7c7491a5cfc50e5:0x35b7fad8eb59ba84!8m2!3d-3.7444222!4d-38.5362296), 15 janeiro 2020, de 19h às 20h30** 

As duas talks mais votadas serão escolhidas.

Submeta sua talk através dos comentários seguindo o formato:

**Título**
**Duração(HH:MM)**
**Descrição curta**
**Descrição longa**

**Comment by cicerohen** [comment]
### Gerenciando conteúdo com o Strapi
Nesta talk irei mostrar o strapi como uma alternativa a outros CMS conhecidos.

**Duração:** 40 minutos

**Comment by AbraaoAlves** [comment]
### Falhar não é uma escolha, é uma certeza

Aprenda de vez como gerenciar seus erros em NodeJS de forma profissional 

**Duração**: 40 minutos

Se você não está falhando 90% do tempo, algo de errado não está muito certo. Abrace a inevitabilidade dos Erros e vamos aprender como programar melhor com eles.
